/**
 * Dank Agent Configuration
 * f

 
 * This file defines your AI agents and their configurations.
 * Run 'dank run' to start all defined agents.-

 
 */

const { createAgent } = require('dank-ai');

module.exports = {
  // Project configuration
  name: 'testDankProject',
  
  // Define your agents
  // Each agent can have custom Docker image configuration for production builds
  agents: [
    // Example 1: Direct Prompting Agent with Event Handlers
    createAgent('prompt-agent')
      .setLLM('openai', {
        apiKey: process.env.OPENAI_API_KEY,
        model: 'gpt-3.5-turbo',
        temperature: 0.7
      })
      .setPrompt('You are a helpful AI assistant. Be concise and friendly in your responses.')
      .setBaseImage('nodejs-20')
      .setPromptingServer({
        protocol: 'http',
        port: 3006
      })
     .setInstanceType("standard")
      // Event handlers for prompt modification and response enhancement
      .addHandler('request_output:start', (data) => {
       
        console.log('[Prompt Agent] Processing prompt:', data.conversationId);
        console.log('[Prompt Agent] Original prompt:', data.prompt);
        
        // Enhance the prompt with context
        const enhancedPrompt = `Context: You are a helpful AI assistant. Please be concise and friendly.\n\nUser Question: ${data.prompt}\n\nPlease provide a clear, helpful response.`;
        
        console.log('[Prompt Agent] Enhanced prompt:', enhancedPrompt);
        
        return {
          prompt: enhancedPrompt
        };
      })
      .addHandler('request_output', (data) => {
        console.log('[Prompt Agent] LLM Response:', {
          prompt: data.prompt,
          finalPrompt: data.finalPrompt,
          promptModified: data.promptModified,
          response: data.response,
          conversationId: data.conversationId,
          processingTime: data.processingTime,
          usage: data.usage,
          model: data.model
        });
      })
      .addHandler('request_output:end', (data) => {
        console.log('[Prompt Agent] Completed in:', data.processingTime + 'ms');
        console.log('[Prompt Agent] Original response:', data.response ? data.response.substring(0, 50) + '...' : 'N/A');
        
        // Enhance the response with metadata
        const enhancedResponse = `${data.response}\n\n---\n🤖 TESTING Generated by Dank Framework Agent\n⏱️ Processing time: ${data.processingTime}ms\n`;
        
        console.log('[Prompt Agent] Enhanced response:', enhancedResponse.substring(0, 100) + '...');
        
        return {
          response: enhancedResponse
        };
      })
      .addHandler('request_output:error', (data) => {
        console.error('[Prompt Agent] Error processing prompt:', data.error);
      })
      .addHandler('output', (data) => {
        console.log('[Prompt Agent] System output:', data);
      })
      .addHandler('error', (error) => {
        console.error('[Prompt Agent] System error:', error);
      })
  ]
};
